# Generated by Django 5.2 on 2025-12-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='absuser',
            name='first_name',
            field=models.CharField(db_column='first_name_user', db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='absuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, db_column='last_login_user', null=True),
        ),
        migrations.AlterField(
            model_name='absuser',
            name='last_name',
            field=models.CharField(db_column='last_name_user', db_index=True, max_length=30),
        ),
    ]
