# Generated by Django 5.2 on 2025-12-11 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIUser', '0002_remove_absuser_username_alter_absuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absuser',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='absuser',
            name='date_joined_user',
            field=models.DateTimeField(db_column='date_joined_user', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='absuser',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login_user', default=None, null=True),
        ),
    ]
